### ISSUE TITLE
Change translation package

### ISSUE THREAD

**Issue by Jannik-dev** [Caeli-technologies/rotary_nl_rye#37]
The package we are depending on says:
"This package is developed for educational purposes only. Do not depend on this package as it may break anytime as it is based on crawling the Google Translate website. Consider buying Official Google Translate API for other types of usage."

Also the translation speed will be increased

Suggest to switch to:
- https://pub.dev/packages/i18n_extension
- or maybe https://pub.dev/packages/flutter_translate

**Comment by rubentalstra** [comment]
foxed
