### ISSUE TITLE
[BUG] rebounds video player

### ISSUE THREAD

**Issue by rubentalstra** [Caeli-technologies/rotary_nl_rye#46]
when you want to make the video player in Rebounds fullscreen

this error is showing up:

![Simulator Screen Shot - iPhone 12 Pro Max (14 4) - 2021-06-22 at 20 03 45](https://user-images.githubusercontent.com/14235001/122976740-ff7dff00-d394-11eb-9d46-bc603a3f487d.png)

**Comment by wick3ds0ul** [comment]
I am unable to reproduce this error.

**Comment by rubentalstra** [comment]
bug solved was a bad video it self
