### ISSUE TITLE
Repository build issue

### ISSUE THREAD

**Issue by ShwetaChauhan18** [Caeli-technologies/rotary_nl_rye#54]
I have fixed your repository build issue.

**Comment by rubentalstra** [comment]
Great. Sorry what issue 😅 I just tested it and there was no build issue so far for me ?

**Comment by ShwetaChauhan18** [comment]
sorry, there was no issue

**Comment by rubentalstra** [comment]
No problem. Feel free to submit anything if you have something. 

That’s why it’s open source 🙌🏼
